[package]
name = "robot6dof-desktop"
version = "1.0.0"
description = "Robot 6 DOF Digital Twin - Desktop App"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
url = "2"

[profile.release]
panic = "abort"
opt-level = "s"
strip = true
